<?php
    if(empty($_POST['name'])){
        skip('login.php','error','管理员名称不得为空');
        exit();
    }
    if(mb_strlen($_POST['name'])>32){
        skip('login.php','error','板块名称不得多于32个字符');
        exit();
    }
    if(mb_strlen($_POST['pw']<6)){
        skip('login.php','error','密码不得少于6位');
        exit();
    }
?>